title: Application of Machine Learning for Creditworthiness in the Financial Industry  
description: By Michael Chen, Yifan Li, Aneesh Navanale, and William Xia under the advisory of Brian Duke and Berk Ustun.

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one

---
layout: temp
---


